version: "3.5"

networks:
  template01.network:
    driver: bridge

volumes:
  db.todo:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - db.todo:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      - template01.network
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate python manage.py runserver 0.0.0.0:8000"
    networks:
      - template01.network
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  # front:
  #   build:
  #     context: backend/
  #     dockerfile: Dockerfile
  #   command: bash -c "python manage.py migrate python manage.py runserver 0.0.0.0:80"
  #   networks:
  #     - template01.network
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - backend