# Generated by Django 4.1.1 on 2023-12-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('list_users', 'List usuários'), ('create_user', 'Create usuário'), ('update_user', 'Update usuário'), ('inactivate_user', 'Delete usuário')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
