# Generated by Django 4.1.1 on 2023-12-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('list_users', 'List users'), ('create_user', 'Create user'), ('update_user', 'Update user'), ('inactivate_user', 'Inativa user')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
