# Generated by Django 4.1.1 on 2023-12-27 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Completed')], default='1', max_length=12)),
                ('title', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=155)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'permissions': (('list_tasks', 'List trasks'), ('create_task', 'Create trask'), ('update_task', 'Update trask'), ('delete_task', 'Delete trask')),
            },
        ),
    ]
